---
name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    name: Test
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Diagnostics
        run: |
          node --version
          npm --version
      - name: Unit Tests
        run: |
          npm install
          npm test
